name: wba
channels:
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.6
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - icu=58.2
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - openssl=1.1.1b
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - adal==1.2.1
    - applicationinsights==0.11.8
    - asn1crypto==0.24.0
    - azure-common==1.1.19
    - azure-graphrbac==0.61.0
    - azure-mgmt-authorization==0.51.1
    - azure-mgmt-containerregistry==2.7.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-resource==2.1.0
    - azure-mgmt-storage==3.1.1
    - azure-nspkg==3.0.2
    - azureml-contrib-explain-model==1.0.33
    - azureml-contrib-notebook==1.0.33
    - azureml-core==1.0.33.1
    - azureml-dataprep==1.1.2
    - azureml-dataprep-native==12.0.1
    - azureml-explain-model==1.0.33
    - azureml-pipeline==1.0.33
    - azureml-pipeline-core==1.0.33
    - azureml-pipeline-steps==1.0.33
    - azureml-sdk==1.0.33
    - azureml-telemetry==1.0.33
    - azureml-train==1.0.33
    - azureml-train-automl==1.0.33
    - azureml-train-core==1.0.33
    - azureml-train-restclients-hyperdrive==1.0.33
    - azureml-widgets==1.0.33
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.1.6
    - boto==2.49.0
    - boto3==1.9.134
    - botocore==1.12.134
    - bz2file==0.98
    - cffi==1.12.3
    - chardet==3.0.4
    - contextlib2==0.5.5
    - cryptography==2.6.1
    - dill==0.2.9
    - distro==1.4.0
    - docker==3.7.2
    - docker-pycreds==0.4.0
    - docutils==0.14
    - dotnetcore2==2.1.8
    - gensim==3.7.2
    - h5py==2.9.0
    - idna==2.8
    - imageio==2.5.0
    - isodate==0.6.0
    - jeepney==0.4
    - jmespath==0.9.4
    - jsonform==0.0.2
    - jsonpickle==1.1
    - jsonsir==0.0.2
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - keras2onnx==1.3.2
    - lightgbm==2.2.1
    - msrest==0.6.6
    - msrestazure==0.6.0
    - ndg-httpsclient==0.5.1
    - networkx==2.3
    - nimbusml==0.6.5
    - numpy==1.16.2
    - oauthlib==3.0.1
    - onnx==1.4.1
    - onnxmltools==1.4.0
    - onnxtk==0.0.1
    - pandas==0.24.2
    - paramiko==2.4.2
    - pathspec==0.5.9
    - pillow==6.0.0
    - protobuf==3.7.1
    - pyasn1==0.4.5
    - pycparser==2.19
    - pyjwt==1.7.1
    - pynacl==1.3.0
    - pyopenssl==19.0.0
    - python-easyconfig==0.1.7
    - pywavelets==1.0.3
    - pyyaml==5.1
    - requests==2.21.0
    - requests-oauthlib==1.2.0
    - resource==0.2.1
    - ruamel-yaml==0.15.89
    - s3transfer==0.2.0
    - scikit-image==0.15.0
    - scikit-learn==0.20.3
    - scipy==1.1.0
    - seaborn==0.9.0
    - secretstorage==3.1.1
    - shap==0.28.5
    - skl2onnx==1.4.5
    - sklearn-pandas==1.7.0
    - smart-open==1.8.2
    - tf2onnx==1.4.1
    - tqdm==4.31.1
    - typing==3.6.6
    - typing-extensions==3.7.2
    - urllib3==1.25
    - websocket-client==0.56.0
    - wheel==0.30.0

